        
        <!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="styls.css">
</head>
<body>
    <table>
        <tr>
            <th>E-Waste Category</th>
            <th>Mark</th>
            <th>Quantity (Kg)</th>
        </tr>
        <tr>
            <td>Monitoring & Control Equipment</td>
            <td><input type="checkbox" name="mark1"></td>
            <td><input type="text" name="quality1"></td>
        </tr>
        <tr>
            <td>Electronical and Electronic Tools</td>
            <td><input type="checkbox" name="mark2"></td>
            <td><input type="text" name="quality2"></td>
        </tr>
        <tr>
            <td>IT and Telecommunications Equipment</td>
            <td><input type="checkbox" name="mark3"></td>
            <td><input type="text" name="quality3"></td>
        </tr>
        <tr>
            <td>Automatic dispensers</td>
            <td><input type="checkbox" name="mark4"></td>
            <td><input type="text" name="quality4"></td>
        </tr>
        <tr>
            <td>Toys, Leisure and Sports Equipment</td>
            <td><input type="checkbox" name="mark5"></td>
            <td><input type="text" name="quality5"></td>
        </tr>
        <tr>
            <td>Household appliaces(large & small)</td>
            <td><input type="checkbox" name="mark6"></td>
            <td><input type="text" name="quality6"></td>
        </tr>
        <tr>
            <td>Consumers electronics</td>
            <td><input type="checkbox" name="mark7"></td>
            <td><input type="text" name="quality7"></td>
        </tr>
        <tr>
            <td>Medical devices</td>
            <td><input type="checkbox" name="mark8"></td>
            <td><input type="text" name="quality8"></td>
        </tr>
        <tr>
            <td>Others</td>
            <td><input type="checkbox" name="mark9"></td>
            <td><input type="text" name="quality9"></td>
            
        
            
        </tr>
        <div class="button">
            <tr><td></td>
              <td>
                <button type="submit">submit</button>
              </td>
           </tr> 
        </div>
        
        
    </table>
</body>
</html>